services:
  netsub:
    build: .
    image: netsub:latest
    container_name: netsub
    restart: unless-stopped
    ports:
      - "8787:8787"
    volumes:
      - ./out:/app/out
    environment:
      - TZ=Asia/Shanghai
